kind: pipeline
type: docker
name: blog

steps:
  - name: test
    image: golang1.12
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

  - name: build
    image: golang1.12
    volumes:
      - name: deps
        path: /go
    commands:
      - go build

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: deps
    temp: {}
