kind: pipeline
name: blog

clone:
  depth: 1

steps:
  - name: test
    image: golang:1.12
    volumes:
      - name: deps
        path: /go
    environment:
      - GO111MODULE: on
      - GOPROXY: https://goproxy.io
    commands:
      - go test

  - name: build
    image: golang:1.12
    volumes:
      - name: deps
        path: /go
    environment:
      - GO111MODULE: on
      - GOPROXY: https://goproxy.io
      - CGO_ENABLED: 0
      - GOOS: linux
      - GOARCH: amd64
    commands:
      - go build -v -a -o bin/server_exec main.go

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: deps
    temp: {}
