kind: pipeline
name: blog

clone:
  depth: 1

steps:
  - name: test
    image: golang:1.12
    volumes:
      - name: deps
        path: /go
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.io
    commands:
      - go test -mod=vendor

  - name: build
    image: golang:1.12
    volumes:
      - name: deps
        path: /go
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.io
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - go build -mod=vendor -v -a -o bin/server_exec main.go

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hub.tencentyun.com/double1996/blog
      registry: hub.tencentyun.com
      dockerfile: ./Dockerfile
      tags: latest

#  - name: deploy
#    image: docker:latest
#    volumes:
#      - name: docker
#        path: /var/run/docker.sock
#    environment:
#      USERNAME:
#        from_secret: docker_username
#      PASSWORD:
#        from_secret: docker_password
#    commands:
#      - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD hub.tencentyun.com
#      - docker pull hub.tencentyun.com/double1996/blog:latest
#      - docker rm -f blog || true
#      - docker run -d  --name blog -p 8001:8001 hub.tencentyun.com/double1996/blog:latest

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: deps
    temp: {}
#  - name: docker
#    host:
#      path: /var/run/docker.sock
