kind: pipeline
name: blog

clone:
  depth: 1

steps:
  - name: test
    image: golang1.12
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

  - name: build
    image: golang1.12
    volumes:
      - name: deps
        path: /go
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o bin/server_exec main.go

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: deps
    temp: {}
