kind: pipeline
name: blog

steps:
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

  - name: build
    image: golang1.13
    volumes:
      - name: deps
        path: /go
    commands:
      - go build
      - name: deps

volumes:
  - name: deps
    temp: {}
